# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [ ]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [ ]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [ ]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [ ]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [ ]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipython-input-1713118361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipython-input-1713118361.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)

In [ ]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipython-input-3000949103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [ ]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipython-input-626038248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

### 🤓 6. Cleaned Data Review

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.describe(include="all")

         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Food": ["Fries", "None", "Nugget", "Pie", ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score    Food
0    Alice      25     2022-01-01  95.5   Fries
1      Bob  thirty     not a date  None    None
2  Charlie      35     2022/03/01  88.0  Nugget
3    David     NaN           None  92.5     Pie
4     None      40  April 5, 2022

In [ ]:
df.isnull()

    Name    Age  Signup Date  Score   Food
0  False  False        False  False  False
1  False  False        False   True  False
2  False  False        False  False  False
3  False   True         True  False  False
4   True  False        False  False  False

In [ ]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
Food           0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score  Food
1    Bob  thirty     not a date  None  None
3  David     NaN           None  92.5   Pie
4   None      40  April 5, 2022

In [ ]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0,
    "Food": "Unknown"
})

      Name     Age    Signup Date Score    Food
0    Alice      25     2022-01-01  95.5   Fries
1      Bob  thirty     not a date   0.0    None
2  Charlie      35     2022/03/01  88.0  Nugget
3    David      -1     1970-01-01  92.5     Pie
4  Unknown      40  April 5, 2022

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [ ]:
df.dropna()

      Name Age Signup Date Score    Food
0    Alice  25  2022-01-01  95.5   Fries
2  Charlie  35  2022/03/01  88.0  Nugget

In [ ]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
Food           object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Food                   object
dtype: object

In [ ]:
df["Name"].fillna("Unknown", inplace=True)
df["Food"].fillna("Unknown", inplace=True)

/tmp/ipython-input-1292993308.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)
/tmp/ipython-input-1292993308.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Food"].fillna("Unknown", inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[ns]
 3   Score        3 non-null      float64
 4   Food         5 non-null      object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 332.0+ bytes

In [ ]:
df.describe(include="all")

         Name        Age          Signup Date      Score   Food
count       5   3.000000                    1   3.000000      5
unique      5        NaN                  NaN        NaN      5
top     Alice        NaN                  NaN        NaN  Fries
freq        1        NaN                  NaN        NaN      1
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000    NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.000000    NaN
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000    NaN
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000    NaN
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000    NaN
max       NaN  40.000000  2022-01-01 00:00:00  95.500000    NaN
std       NaN   7.637626                  NaN   3.774917    NaN

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |