# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [3]:
import pandas as pd
df = pd.read_csv("../data/students.csv")
df.head()

   id first_name  last_name       gender  Math_score  Science_score
0   1  Melisenda   Erricker  Genderqueer        65.0           81.0
1   2      Goran  Grzelczyk         Male        67.0           56.0
2   3   Mitchael      Badby         Male        71.0           90.0
3   4      Helli     Brosch       Female        73.0           88.0
4   5      Aimee   Morfield       Female         NaN            NaN

### 🔢 2. Sorting Data

In [5]:
# Sort by math_score
#df.sort_values(by="math_score")
df.sort_values(by="Math_score")

      id  first_name last_name  gender  Math_score  Science_score
449  450      Rowena  Flavelle  Female        55.0            NaN
938  939  Sebastiano    Jenken    Male        55.0           96.0
892  893      Brooke   Dyerson    Male        55.0           94.0
891  892      Martha    Lafont  Female        55.0           58.0
188  189    Thaddeus   Bilbery    Male        55.0           59.0
..   ...         ...       ...     ...         ...            ...
963  964     Ninetta  Alastair  Female         NaN            NaN
964  965       Marne    Putson  Female         NaN           78.0
965  966      Nalani  Eathorne  Female         NaN           63.0
980  981         Ken   Dowsing    Male         NaN           59.0
987  988       Storm     Muino  Female         NaN           88.0

[1000 rows x 6 columns]

In [6]:
# Sort by science_score descending
#df.sort_values(by="science_score", ascending=False)
df.sort_values(by="Science_score", ascending=False)

      id first_name    last_name       gender  Math_score  Science_score
9     10     Jasper        Farey         Male        89.0          100.0
912  913      Aggie  Prendergast       Female        59.0          100.0
903  904      Abbie       Feckey       Female        88.0          100.0
50    51    Valerye  Wapplington       Female        63.0          100.0
544  545    Abagail      Crowche  Genderfluid        82.0          100.0
..   ...        ...          ...          ...         ...            ...
928  929      Elset       Jaquin       Female        78.0            NaN
960  961    Derrick      Baudrey   Non-binary        92.0            NaN
963  964    Ninetta     Alastair       Female         NaN            NaN
974  975    Mellisa       Kaysor       Female        81.0            NaN
986  987    Doralia      Haitlie       Female        75.0            NaN

[1000 rows x 6 columns]

In [8]:
# Sort by multiple columns
#df.sort_values(by=["science_score", "math_score"], ascending=[False, True])
#In my students.csv the colum names are Science_score ans Math_score
df.sort_values(by=["Science_score", "Math_score"], ascending=[False, True])

      id first_name    last_name  gender  Math_score  Science_score
499  500      Nicki       Touhig  Female        59.0          100.0
912  913      Aggie  Prendergast  Female        59.0          100.0
50    51    Valerye  Wapplington  Female        63.0          100.0
662  663    Agretha     Eggerton  Female        68.0          100.0
87    88      Tobey        Giggs  Female        73.0          100.0
..   ...        ...          ...     ...         ...            ...
769  770     Henrik     Jaszczak    Male         NaN            NaN
787  788    Whitney    Willerton  Female         NaN            NaN
894  895    Ophelia      Bugbird  Female         NaN            NaN
896  897       Wolf      Chatain    Male         NaN            NaN
963  964    Ninetta     Alastair  Female         NaN            NaN

[1000 rows x 6 columns]

### 🧪 3. Filtering with Conditions

In [9]:
# Who scored at least 90 in math?
#df[df["math_score"] >= 90]
df[df["Math_score"] >= 90]

       id  first_name   last_name       gender  Math_score  Science_score
5       6      Colene       Reihm  Genderfluid        98.0           69.0
7       8        Pier   Castanone       Female        92.0           87.0
13     14    Horatius    Merricks         Male       100.0           90.0
21     22       Ailee  Saintsbury       Female        92.0           66.0
22     23  Claybourne     Izachik         Male       100.0           77.0
..    ...         ...         ...          ...         ...            ...
991   992        Gabi       Rushe       Female        98.0           75.0
992   993     Stanley      Malter   Non-binary        92.0           63.0
997   998         Clo  Giacovazzo       Female        96.0           80.0
998   999        Zack     Parslow         Male        90.0           68.0
999  1000   Miguelita    Crosdill       Female        96.0           82.0

[209 rows x 6 columns]

In [10]:
# Who scored less than 70 in either subject?
#df[(df["math_score"] < 70) | (df["science_score"] < 70)]
df[(df["Math_score"] < 70) | (df["Science_score"] < 70)]

      id first_name    last_name       gender  Math_score  Science_score
0      1  Melisenda     Erricker  Genderqueer        65.0           81.0
1      2      Goran    Grzelczyk         Male        67.0           56.0
5      6     Colene        Reihm  Genderfluid        98.0           69.0
6      7   Stefanie      Skepper       Female        67.0           89.0
8      9     Elicia      Cranmor      Agender        59.0           89.0
..   ...        ...          ...          ...         ...            ...
990  991       Kyle      Rickell         Male        71.0           62.0
992  993    Stanley       Malter   Non-binary        92.0           63.0
993  994    Silvano       Bolley         Male        85.0           56.0
994  995    Vincent  Yakebovitch         Male        58.0           68.0
998  999       Zack      Parslow         Male        90.0           68.0

[505 rows x 6 columns]

### 🔗 4. Combining Filters

In [11]:
# Students with B+ or higher in both
#df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]
df[(df["Math_score"] >= 87) & (df["Science_score"] >= 87)]

      id first_name  last_name  gender  Math_score  Science_score
7      8       Pier  Castanone  Female        92.0           87.0
9     10     Jasper      Farey    Male        89.0          100.0
13    14   Horatius   Merricks    Male       100.0           90.0
45    46  Georgiana   Whitford  Female        91.0           88.0
53    54       Skip    Brabant    Male        98.0           89.0
..   ...        ...        ...     ...         ...            ...
878  879     Ashbey   Aiskrigg    Male        94.0           87.0
888  889      Meggy     Govier  Female        89.0           89.0
903  904      Abbie     Feckey  Female        88.0          100.0
915  916   Tabbitha     Brayne  Female        99.0           93.0
967  968      Kenna    Galfour  Female        87.0           94.0

[63 rows x 6 columns]

### 🧾 5. Using `.query()` for Readability

In [13]:
# Same query using .query()
#df.query("math_score >= 87 and science_score >= 87")
df.query("Math_score >= 87 and Science_score >= 87")

      id first_name  last_name  gender  Math_score  Science_score
7      8       Pier  Castanone  Female        92.0           87.0
9     10     Jasper      Farey    Male        89.0          100.0
13    14   Horatius   Merricks    Male       100.0           90.0
45    46  Georgiana   Whitford  Female        91.0           88.0
53    54       Skip    Brabant    Male        98.0           89.0
..   ...        ...        ...     ...         ...            ...
878  879     Ashbey   Aiskrigg    Male        94.0           87.0
888  889      Meggy     Govier  Female        89.0           89.0
903  904      Abbie     Feckey  Female        88.0          100.0
915  916   Tabbitha     Brayne  Female        99.0           93.0
967  968      Kenna    Galfour  Female        87.0           94.0

[63 rows x 6 columns]

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [ ]:
#Sort the dataset by first name alphabetically
sorted_df = df.sort_values(by=['first_name'], ascending=True)
print(sorted_df[:19]) #first 19 rows of the data
#print(sorted_df.head(10)) ##first 10 rows of the data

      id first_name    last_name       gender  Math_score  Science_score
962  963      Aaron       Rieger         Male        86.0           69.0
584  585         Ab        Erdes         Male         NaN           66.0
544  545    Abagail      Crowche  Genderfluid        82.0          100.0
856  857      Abbey      Fibbens         Male        60.0           93.0
903  904      Abbie       Feckey       Female        88.0          100.0
303  304       Abie      Sussans         Male        61.0           71.0
447  448    Abrahan     Aicheson         Male        84.0            NaN
663  664      Abran      Novelli         Male         NaN           63.0
955  956        Ada         Hort       Female        84.0           80.0
63    64       Addi       Darbey       Female         NaN           82.0
485  486      Adina    Blackhall       Female         NaN           69.0
178  179     Agatha   MacCaughey       Female        69.0           81.0
912  913      Aggie  Prendergast       Female        59.0          100.0
956  957    Agnella     Gilgryst       Female        78.0           82.0
261  262    Agnesse      Brenard       Female        79.0           71.0
662  663    Agretha     Eggerton       Female        68.0          100.0
121  122   Aguistin      Digance         Male        74.0            NaN
21    22      Ailee   Saintsbury       Female        92.0           66.0
4      5      Aimee     Morfield       Female         NaN            NaN

In [19]:
#Find students with the same math and science score
#df[(df["Math_score"] < 70) | (df["Science_score"] < 70)]
df[(df["Math_score"]) == (df["Science_score"])]

      id  first_name   last_name       gender  Math_score  Science_score
122  123       Rasia     Lawless       Female        79.0           79.0
159  160      Alicea      Steele       Female        90.0           90.0
189  190       Rabbi     Cleaves      Agender        76.0           76.0
320  321       Artie     Huntall         Male        91.0           91.0
413  414    Vivianna      Graben       Female        73.0           73.0
479  480       Shena     Habbema       Female        93.0           93.0
588  589     Therese  Leadbitter       Female        58.0           58.0
624  625      Kassia      Blasio       Female        76.0           76.0
631  632     Vidovic    Stoffler         Male        60.0           60.0
643  644  Alessandra     Folshom       Female        79.0           79.0
685  686        Ania       Frear  Genderqueer        88.0           88.0
824  825      Traver     Cockney         Male        69.0           69.0
835  836        Bone     Viscovi         Male        94.0           94.0
843  844       Kaine       Kless         Male        63.0           63.0
888  889       Meggy      Govier       Female        89.0           89.0
899  900        Fina      Yarham       Female        63.0           63.0

In [22]:
#Use `.query()` to find students who scored over 95 in *either* subject
#df.query("Math_score >= 87 and Science_score >= 87")
df.query("Math_score > 95 | Science_score > 95")

       id  first_name    last_name       gender  Math_score  Science_score
5       6      Colene        Reihm  Genderfluid        98.0           69.0
9      10      Jasper        Farey         Male        89.0          100.0
13     14    Horatius     Merricks         Male       100.0           90.0
22     23  Claybourne      Izachik         Male       100.0           77.0
26     27         Ash  Desesquelle         Male        96.0           82.0
..    ...         ...          ...          ...         ...            ...
981   982     Chancey      Barreau         Male        97.0           79.0
985   986     Kordula      Beushaw       Female        61.0           96.0
991   992        Gabi        Rushe       Female        98.0           75.0
997   998         Clo   Giacovazzo       Female        96.0           80.0
999  1000   Miguelita     Crosdill       Female        96.0           82.0

[166 rows x 6 columns]

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [2]:
import pandas as pd
df = pd.read_csv("../data/survey.csv")
df.head()
#print(df.columns)

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [3]:
# Sort by the most recent signup date
df.sort_values(by="survey_date", ascending=False)

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
78,S10078,24,NaN,Undeclared,NaN,12.5,NaN,29-Sep-2025,N,2027,>$100k,NaN,No,NaN,Go,NaN
58,S10058,21,Prefer not to say,CS,NaN,20,5,29-Nov-2025,Y,2030,$50k-$75k,1,0,105%,Rust,NaN
38,S10038,NaN,Prefer not to say,Business,5.1,NaN,NaN,28-Sep-2025,NaN,NaN,$50k-$75k,NaN,TRUE,NaN,JavaScript,NaN
41,S10041,twenty,Prefer not to say,History,5.1,12.5,2,25-Sep-2025,N,NaN,$25k-$50k,38,Yes,105%,Python,Lectures are 🔥
96,S10096,24,NaN,Math,NaN,NaN,NaN,24-Nov-2025,NaN,twenty28,>$100k,NaN,0,NaN,NaN,Lectures are 🔥
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,S10102,19,Female,Business,NaN,-3,NaN,NaN,No,2028,NaN,0,TRUE,NaN,C++,NaN
105,S10105,25,NaN,History,NaN,ten,NaN,NaN,Y,2026,$25k-$50k,0,0,105%,JavaScript,Need more examples.
106,S10106,20,Non-binary,Business,5.1,0,3,NaN,Yes,2027,$50k-$75k,-5,FALSE,NaN,NaN,Lectures are 🔥
111,S10111,23,Female,Undeclared,3.75,12.5,NaN,NaN,Yes,twenty28,Prefer not to say,NaN,0,NaN,Python,NaN
119,S10119,22,NaN,NaN,NaN,NaN,five,NaN,N,twenty28,$50k-$75k,NaN,NaN,NaN,NaN,Too much homework.

In [15]:
# Filter out anyone who didn't complete the survey (nulls or "N/A")
import pandas as pd
import numpy as np
# Replace 'N/A' strings with actual NaN values
#df.replace('NaN', np.nan, inplace=True)
# Filter out rows where 'survey_date' is null
df_cleaned = df.dropna(subset=['survey_date'])
print(df_cleaned)
# Drop rows where ANY column has a null/NaN value
#cleaned_df = df.dropna()
#df[(df["survey_date"] != "Nan") & (df["gpa"] != "Nan")]
#df[(df["survey_date"] != "NaN")]

    student_id  age             gender             major   gpa  \
0       S10000  NaN               Male  Computer Science   NaN
2       S10002   23               Male      Data Science   NaN
4       S10004  NaN             Female           CompSci   NaN
6       S10006  NaN  Prefer not to say          Business   NaN
7       S10007  NaN         Non-binary           CompSci  3.69
..         ...  ...                ...               ...   ...
114     S10114  NaN         Non-binary                CS   NaN
115     S10115   22             Female           History  3.75
116     S10116   18         Non-binary      Data Science   NaN
117     S10117  NaN                NaN           Biology   3.2
118     S10118   22         Non-binary           History   5.1

    study_hours_per_week satisfaction_1_5  survey_date dorm_resident  \
0                    NaN                2   2025-13-40           Yes
2                     20                5   2025-13-40           NaN
4                      0                5   2025-13-40           Yes
6                    NaN                2   2025-09-07             N
7                    NaN             five   2025-13-40           NaN
..                   ...              ...          ...           ...
114                  NaN              NaN  08-Nov-2025           Yes
115                  NaN              NaN  01-Nov-2025           Yes
116                 12.5              NaN   09/28/2025           Yes
117                    0              NaN   2025-10-31            No
118                  ten             five   09/05/2025           NaN

    expected_grad_year       income_range commute_minutes clubs_member  \
0                 2027             >$100k              54         TRUE
2                 2027         $75k-$100k             NaN          NaN
4                 2029  Prefer not to say              41           No
6                 2028                NaN               0        FALSE
7                 2027          $50k-$75k             NaN            0
..                 ...                ...             ...          ...
114                NaN  Prefer not to say             NaN            0
115                NaN          $50k-$75k               0            1
116                NaN             >$100k             NaN          Yes
117               2028              <$25k             NaN            1
118               2028              <$25k              -5          Yes

    attendance_rate favorite_language             comments
0              105%        JavaScript     Love the course.
2               64%        JavaScript                  NaN
4               NaN            Python                  NaN
6               NaN               SQL  Need more examples.
7               NaN              Rust     Love the course.
..              ...               ...                  ...
114            105%        JavaScript   Too much homework.
115             NaN                Go                  NaN
116             75%        JavaScript     Love the course.
117             NaN               NaN                  NaN
118             62%              Rust                  NaN

[88 rows x 16 columns]

In [31]:
#Use `.query()` to select rows with a specific condition of your choice
#df.query("age > 20 | gpa > 3.5")
#df.query("gender == 'Male'")
#df.query("age > '20'")
#df.query("gender == 'Male' and age > '20'")
df.query("age > '20' | gpa > '3.5'")

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
5,S10005,22,Male,Biology,"4,0",20,4,NaN,NaN,twenty28,$25k-$50k,NaN,No,NaN,Rust,NaN
7,S10007,NaN,Non-binary,CompSci,3.69,NaN,five,2025-13-40,NaN,2027,$50k-$75k,NaN,0,NaN,Rust,Love the course.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,S10111,23,Female,Undeclared,3.75,12.5,NaN,NaN,Yes,twenty28,Prefer not to say,NaN,0,NaN,Python,NaN
112,S10112,NaN,Male,Undeclared,5.1,28,NaN,2025-13-40,Yes,2029,Prefer not to say,-5,Yes,NaN,SQL,NaN
115,S10115,22,Female,History,3.75,NaN,NaN,01-Nov-2025,Yes,NaN,$50k-$75k,0,1,NaN,Go,NaN
118,S10118,22,Non-binary,History,5.1,ten,five,09/05/2025,NaN,2028,<$25k,-5,Yes,62%,Rust,NaN
119,S10119,22,NaN,NaN,NaN,NaN,five,NaN,N,twenty28,$50k-$75k,NaN,NaN,NaN,NaN,Too much homework.

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |