# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [2]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [22]:
# Create a small CSV for my practice
Life_style = """Name,Age,Occupation,Favorite_food,TV_show
Tracy,29,Student,Pasta,Crown
Robbert,36,Doctor,Burger,Survival
Clara,57,Soliciter,Kebab,Royals
"""
with open("Life_style.csv", "w") as f:
    f.write(Life_style)

# Read Life_style.CSV file into DataFrame
df = pd.read_csv("Life_style.csv")
df

      Name  Age Occupation Favorite_food   TV_show
0    Tracy   29    Student         Pasta     Crown
1  Robbert   36     Doctor        Burger  Survival
2    Clara   57  Soliciter         Kebab    Royals

## 2. Exploring DataFrames

In [23]:
# Look at the first rows
df.head()

      Name  Age Occupation Favorite_food   TV_show
0    Tracy   29    Student         Pasta     Crown
1  Robbert   36     Doctor        Burger  Survival
2    Clara   57  Soliciter         Kebab    Royals

In [24]:
# Info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           3 non-null      str
 1   Age            3 non-null      int64
 2   Occupation     3 non-null      str
 3   Favorite_food  3 non-null      str
 4   TV_show        3 non-null      str
dtypes: int64(1), str(4)
memory usage: 252.0 bytes

In [25]:
# Summary statistics
df.describe()

             Age
count   3.000000
mean   40.666667
std    14.571662
min    29.000000
25%    32.500000
50%    36.000000
75%    46.500000
max    57.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [26]:
df.describe()

             Age
count   3.000000
mean   40.666667
std    14.571662
min    29.000000
25%    32.500000
50%    36.000000
75%    46.500000
max    57.000000

## 3. Writing CSV Files

In [27]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

Life_style.csv  own.csv     students.csv
my_data.csv     scores.csv  students_copy.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [28]:
df.to_csv("my_data.csv", index=False)
%ls *.csv

Life_style.csv  own.csv     students.csv
my_data.csv     scores.csv  students_copy.csv

## 4. Reading Excel Files

In [29]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

      Name  Age Occupation Favorite_food   TV_show
0    Tracy   29    Student         Pasta     Crown
1  Robbert   36     Doctor        Burger  Survival
2    Clara   57  Soliciter         Kebab    Royals

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [30]:
#Save to Excel
df.to_excel("my_data.xlsx", index=False)

# Read Excel file
pd.read_excel("my_data.xlsx")

      Name  Age Occupation Favorite_food   TV_show
0    Tracy   29    Student         Pasta     Crown
1  Robbert   36     Doctor        Burger  Survival
2    Clara   57  Soliciter         Kebab    Royals

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.